# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/razikszy/CLionProjects/MotherInLaw

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/razikszy/CLionProjects/MotherInLaw

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/razikszy/CLionProjects/MotherInLaw/CMakeFiles /home/razikszy/CLionProjects/MotherInLaw//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/razikszy/CLionProjects/MotherInLaw/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MotherInLaw

# Build rule for target.
MotherInLaw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MotherInLaw
.PHONY : MotherInLaw

# fast build rule for target.
MotherInLaw/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MotherInLaw.dir/build.make CMakeFiles/MotherInLaw.dir/build
.PHONY : MotherInLaw/fast

#=============================================================================
# Target rules for targets named run_tests

# Build rule for target.
run_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_tests
.PHONY : run_tests

# fast build rule for target.
run_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/build
.PHONY : run_tests/fast

export.o: export.cpp.o
.PHONY : export.o

# target to build an object file
export.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MotherInLaw.dir/build.make CMakeFiles/MotherInLaw.dir/export.cpp.o
.PHONY : export.cpp.o

export.i: export.cpp.i
.PHONY : export.i

# target to preprocess a source file
export.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MotherInLaw.dir/build.make CMakeFiles/MotherInLaw.dir/export.cpp.i
.PHONY : export.cpp.i

export.s: export.cpp.s
.PHONY : export.s

# target to generate assembly for a file
export.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MotherInLaw.dir/build.make CMakeFiles/MotherInLaw.dir/export.cpp.s
.PHONY : export.cpp.s

imageclass.o: imageclass.cpp.o
.PHONY : imageclass.o

# target to build an object file
imageclass.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MotherInLaw.dir/build.make CMakeFiles/MotherInLaw.dir/imageclass.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/imageclass.cpp.o
.PHONY : imageclass.cpp.o

imageclass.i: imageclass.cpp.i
.PHONY : imageclass.i

# target to preprocess a source file
imageclass.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MotherInLaw.dir/build.make CMakeFiles/MotherInLaw.dir/imageclass.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/imageclass.cpp.i
.PHONY : imageclass.cpp.i

imageclass.s: imageclass.cpp.s
.PHONY : imageclass.s

# target to generate assembly for a file
imageclass.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MotherInLaw.dir/build.make CMakeFiles/MotherInLaw.dir/imageclass.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/imageclass.cpp.s
.PHONY : imageclass.cpp.s

imageclass_test.o: imageclass_test.cpp.o
.PHONY : imageclass_test.o

# target to build an object file
imageclass_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/imageclass_test.cpp.o
.PHONY : imageclass_test.cpp.o

imageclass_test.i: imageclass_test.cpp.i
.PHONY : imageclass_test.i

# target to preprocess a source file
imageclass_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/imageclass_test.cpp.i
.PHONY : imageclass_test.cpp.i

imageclass_test.s: imageclass_test.cpp.s
.PHONY : imageclass_test.s

# target to generate assembly for a file
imageclass_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/imageclass_test.cpp.s
.PHONY : imageclass_test.cpp.s

import.o: import.cpp.o
.PHONY : import.o

# target to build an object file
import.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MotherInLaw.dir/build.make CMakeFiles/MotherInLaw.dir/import.cpp.o
.PHONY : import.cpp.o

import.i: import.cpp.i
.PHONY : import.i

# target to preprocess a source file
import.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MotherInLaw.dir/build.make CMakeFiles/MotherInLaw.dir/import.cpp.i
.PHONY : import.cpp.i

import.s: import.cpp.s
.PHONY : import.s

# target to generate assembly for a file
import.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MotherInLaw.dir/build.make CMakeFiles/MotherInLaw.dir/import.cpp.s
.PHONY : import.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MotherInLaw.dir/build.make CMakeFiles/MotherInLaw.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MotherInLaw.dir/build.make CMakeFiles/MotherInLaw.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MotherInLaw.dir/build.make CMakeFiles/MotherInLaw.dir/main.cpp.s
.PHONY : main.cpp.s

mathcalculate.o: mathcalculate.cpp.o
.PHONY : mathcalculate.o

# target to build an object file
mathcalculate.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MotherInLaw.dir/build.make CMakeFiles/MotherInLaw.dir/mathcalculate.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/mathcalculate.cpp.o
.PHONY : mathcalculate.cpp.o

mathcalculate.i: mathcalculate.cpp.i
.PHONY : mathcalculate.i

# target to preprocess a source file
mathcalculate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MotherInLaw.dir/build.make CMakeFiles/MotherInLaw.dir/mathcalculate.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/mathcalculate.cpp.i
.PHONY : mathcalculate.cpp.i

mathcalculate.s: mathcalculate.cpp.s
.PHONY : mathcalculate.s

# target to generate assembly for a file
mathcalculate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MotherInLaw.dir/build.make CMakeFiles/MotherInLaw.dir/mathcalculate.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/mathcalculate.cpp.s
.PHONY : mathcalculate.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... MotherInLaw"
	@echo "... run_tests"
	@echo "... export.o"
	@echo "... export.i"
	@echo "... export.s"
	@echo "... imageclass.o"
	@echo "... imageclass.i"
	@echo "... imageclass.s"
	@echo "... imageclass_test.o"
	@echo "... imageclass_test.i"
	@echo "... imageclass_test.s"
	@echo "... import.o"
	@echo "... import.i"
	@echo "... import.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mathcalculate.o"
	@echo "... mathcalculate.i"
	@echo "... mathcalculate.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

