name: MotherInLaw

on: [pull_request, workflow_dispatch]

jobs:
  password-check:
    runs-on: ubuntu-latest
    env:
      path: MotherInLaw/build
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: Create build directory
      run: mkdir ${{ env.path }}
    - name: Compile
      working-directory: ${{ env.path }}
      run: |
        cmake ..
        make
