name: MotherInLaw

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
env:
  BUILD_TYPE: Release
  CLANG_TIDY_VERSION: 13
  CMAKE_MAKE_PROGRAM: cmake
      
jobs:
  MotherInLaw:
    runs-on: ubuntu-latest
    env:
      path: build
    steps:
    - name: Install depencies for vcpkg
      run: |
        sudo apt-get install at-spi2-core x11-xserver-utils
    - name: Install vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        vcpkg install catch2
    - name: Install opencv
      run: |
        vcpkg install opencv
    - name: Check out code
      uses: actions/checkout@master
    - name: Create build directory
      run: mkdir ${{ env.path }}
    - name: Compile
      working-directory: ${{ env.path }}
      run: |
        cmake ..
      
