name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-20.04
 

    steps:
      - uses: actions/checkout@v2

      - name: Create Build Environment
        run: mkdir $GITHUB_WORKSPACE/molfunc/build

      - name: Configure CMake
        shell: bash
        run: cd $GITHUB_WORKSPACE/molfunc/build && cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE


      - name: Build
        shell: bash
        run: cd $GITHUB_WORKSPACE/molfunc/build && cmake --build . --config $BUILD_TYPE

      - name: Test
        shell: bash
        run: cd $GITHUB_WORKSPACE/molfunc/build && ctest -C $BUILD_TYPE --extra-verbose
